pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') // Jenkins stored credentials id
        DOCKER_IMAGE_NAME = 'silvy08/insure-me-app'
        GIT_REPO = 'https://github.com/StarAgileDevOpsTraining/star-agile-insurance-project.git'
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning GitHub repository...'
                git branch: 'main', url: "${env.GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t $DOCKER_IMAGE_NAME:latest .'
            }
        }

        stage('Login to Docker Hub') {
            steps {
                echo 'Logging into Docker Hub...'
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                sh 'docker push $DOCKER_IMAGE_NAME:latest'
            }
        }

        stage('Deploy Application') {
            steps {
                echo 'Deploying application using Ansible...'
                sh 'ansible-playbook -i ansible/inventory ansible/playbook.yml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            sh 'docker logout'
            cleanWs()
        }
    }
}
