---
- name: Configure Insure Me EC2 instance
  hosts: testserver
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - java-11-openjdk
          - git
          - docker
          - python3  # required for Ansible on remote hosts
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Jenkins agent
      shell: |
        mkdir -p /home/ec2-user/jenkins
        curl -o /home/ec2-user/jenkins/agent.jar http://<jenkins-server-ip>:8080/jnlpJars/agent.jar
      args:
        creates: /home/ec2-user/jenkins/agent.jar

    - name: Change ownership to ec2-user
      file:
        path: /home/ec2-user/jenkins
        owner: ec2-user
        group: ec2-user
        recurse: yes
